name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build & Test
        run: |
          docker pull postgres:16.2 &
          docker pull redis:7-alpine &
          ./gradlew build --build-cache
